version: "3.8"
services:
  portainer-ce:
    image: portainer/portainer-ce:latest
    container_name: portainer-ce
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - 9000:9000
    networks:
      - intranet

  mysql:
    image: mysql:5.7
    container_name: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: ${DOCKER_DB_USER}
      MYSQL_DATABASE: ${DOCKER_DB_DATABASE}
      MYSQL_PASSWORD: ${DOCKER_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DOCKER_DB_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - ${DOCKER_DB_PORT}
    networks:
      - intranet

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mysql
    ports:
      - 8081:80
    networks:
      - intranet

  dolos:
    build: .
    container_name: dolos
    env_file: .env
    restart: always
    volumes:
      - ./src:/dolos/src
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    networks:
      - intranet

networks:
  intranet:

volumes:
  portainer_data:
  mysql_data:
